const $=id=>document.getElementById(id);let current='dashboard';
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function toast(s){const t=$('toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',3000)}
function show(id){current=id;document.querySelectorAll('main section').forEach(x=>x.hidden=x.id!==id);$('title').textContent={dashboard:'Dashboard',diagnostics:'Diagnostics',whatsapp:'WhatsApp / Baileys',tunnel:'Cloudflare Tunnel',pm2:'PM2 / System',logs:'Logs'}[id]||'Control Center';if(id==='whatsapp')loadWA();if(id==='tunnel')loadTunnel();if(id==='pm2')loadPM2();if(id==='logs')loadLogs();if(id==='diagnostics')diagnose()}
function badge(v){return v?'CONNECTED':'DOWN'}
async function refresh(){try{const d=await api('/admin/api/status');$('wa').textContent=badge(d.whatsapp.connected);$('wa').className='metric '+(d.whatsapp.connected?'ok':'bad');$('waSub').textContent=d.whatsapp.status||'Baileys socket';$('tun').textContent=d.tunnel.connected?'ONLINE':'DOWN';$('tun').className='metric '+(d.tunnel.connected?'ok':'bad');$('tunSub').textContent=d.tunnel.url||'No tunnel URL detected';$('api').textContent='ONLINE';$('api').className='metric ok';$('apiSub').textContent=`Node ${d.system.node}`;$('uptime').textContent=d.system.uptimeHuman;$('sysSub').textContent=`RAM ${d.system.memory} • Disk ${d.system.disk}`;const checks=d.checks||{};$('checks').innerHTML=Object.entries(checks).map(([k,v])=>`<div class="check"><span>${k}</span><strong class="${v.ok?'ok':'bad'}">${v.ok?'✓ OK':'✗ FAIL'}</strong></div>`).join('');$('overall').textContent=d.overall.label;$('overall').className='badge '+(d.overall.ok?'ok':d.overall.warning?'warn':'bad')}catch(e){$('overall').textContent='SERVER ERROR';$('overall').className='badge bad';toast(e.message)}}
async function diagnose(){try{const d=await api('/admin/api/diagnostics');$('diag').innerHTML=Object.entries(d.checks).map(([k,v])=>`<div class="check"><span>${k}<small class="muted"> ${v.detail||''}</small></span><strong class="${v.ok?'ok':'bad'}">${v.ok?'✓':'✗'}</strong></div>`).join('');toast(`${d.passed}/${d.total} checks passed`)}catch(e){toast(e.message)}}
async function loadWA(){try{const d=await api('/admin/api/status');$('waDetail').innerHTML=`<p>State: <b class="${d.whatsapp.connected?'ok':'bad'}">${d.whatsapp.status}</b></p><p class="muted">Socket object: ${d.whatsapp.socket?'present':'missing'} · Auth: ${d.whatsapp.auth?'available':'unknown'}</p>`}catch(e){toast(e.message)}loadGroups()}
async function loadGroups(){try{const d=await api('/admin/api/groups');$('groups').innerHTML=d.groups?.length?'<table class="table"><tr><th>Name</th><th>JID</th></tr>'+d.groups.map(g=>`<tr><td>${escapeHtml(g.name)}</td><td>${escapeHtml(g.id)}</td></tr>`).join('')+'</table>':'No groups returned.'}catch(e){$('groups').textContent=e.message}}
async function loadTunnel(){try{const d=await api('/admin/api/tunnel');$('tunnelDetail').innerHTML=`<p>Status: <b class="${d.connected?'ok':'bad'}">${d.connected?'ONLINE':'OFFLINE'}</b></p><p>Public URL: <b>${escapeHtml(d.url||'Not detected')}</b></p><p>Local target: ${escapeHtml(d.localTarget)}</p><p class="muted">Process: ${escapeHtml(d.process||'not detected')}</p>`}catch(e){toast(e.message)}}
async function loadPM2(){try{const d=await api('/admin/api/pm2');$('pm2data').innerHTML='<table class="table"><tr><th>Name</th><th>Status</th><th>Restarts</th><th>Memory</th><th>Action</th></tr>'+d.processes.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td class="${p.status==='online'?'ok':'bad'}">${escapeHtml(p.status)}</td><td>${p.restarts}</td><td>${p.memory}</td><td><button onclick="restartNamed('${encodeURIComponent(p.name)}')">Restart</button></td></tr>`).join('')+'</table>';$('machine').innerHTML=`<p>Hostname: ${escapeHtml(d.machine.hostname)}</p><p>CPU: ${d.machine.cpu}% · RAM: ${escapeHtml(d.machine.memory)} · Disk: ${escapeHtml(d.machine.disk)}</p>`}catch(e){toast(e.message)}}
async function loadLogs(){try{const d=await api('/admin/api/logs');$('logsBox').textContent=d.logs||'No logs';$('logsBox').scrollTop=$('logsBox').scrollHeight}catch(e){$('logsBox').textContent=e.message}}
async function action(path,label){try{const d=await api(path,{method:'POST'});toast(d.message||`${label}: OK`);setTimeout(refresh,500)}catch(e){toast(`${label}: ${e.message}`)}}
async function restartNamed(name){if(!confirm('Restart this PM2 process?'))return;try{const d=await api('/admin/api/pm2/restart',{method:'POST',body:JSON.stringify({name:decodeURIComponent(name)})});toast(d.message||'Restart requested');setTimeout(loadPM2,1500)}catch(e){toast(e.message)}}
function restartBot(){if(confirm('Restart the bot PM2 process?'))action('/admin/api/bot/restart','Restart bot')}
function manualUrl(){$('modal').style.display='flex'}function closeModal(){$('modal').style.display='none'}
async function saveManual(){const url=$('manualInput').value.trim();try{const d=await api('/admin/api/tunnel/manual-url',{method:'POST',body:JSON.stringify({url})});closeModal();toast(d.message||'URL reported');loadTunnel()}catch(e){toast(e.message)}}
async function repair(){if(!confirm('Run safe automatic repairs?'))return;try{const d=await api('/admin/api/repair',{method:'POST'});toast(d.message||'Repair complete');setTimeout(refresh,1200)}catch(e){toast(e.message)}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
refresh();setInterval(refresh,10000);